name             'csync2'
maintainer       'Heavy Water Operations, LLC'
maintainer_email 'support@hw-ops.com'
license          'Apache-2.0'
description      'Installs/Configures csync2'
version          '0.1.0'
